"""privacy_request_workflow

Revision ID: 7512a2bf2e23
Revises: d6227491fb78
Create Date: 2026-09-22 22:57:17.696366
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "7512a2bf2e23"
down_revision: str | Sequence[str] | None = "d6227491fb78"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "privacy_requests",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("customer_id", sa.String(length=36), nullable=False),
        sa.Column("request_type", sa.String(length=30), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("provider_customer_id", sa.String(length=120), nullable=True),
        sa.Column("evidence_reference", sa.String(length=500), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("processed_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["customer_id"],
            ["customers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_privacy_requests_customer_id"), "privacy_requests", ["customer_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_privacy_requests_customer_id"), table_name="privacy_requests")
    op.drop_table("privacy_requests")
    # ### end Alembic commands ###
